headers = []
redirects = []

[functions]

[functions."*"]

[[plugins]]
origin = "default"
package = "@netlify/angular-runtime"

[plugins.inputs]

[build]
base = "rwdfw-frontend"
publishOrigin = "inline"
commandOrigin = "ui"
command = "npm run build"
publish = "dist/rwdfw/browser"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]